# Generated by Django 4.2 on 2024-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customizeuser',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
