# Generated by Django 4.2 on 2023-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeuser',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
    ]
