# Generated by Django 4.2 on 2023-04-08 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customizeuser_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_cancelled_by_passager', models.BooleanField(default=False, verbose_name='Annulé par le passager')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Passager')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.path', verbose_name='Trajet')),
            ],
        ),
    ]
