# Generated by Django 4.2 on 2023-04-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30, verbose_name="Nom de l'école")),
                ('school_adress', models.CharField(max_length=30, verbose_name="Adresse de l'école")),
                ('school_phone', models.CharField(max_length=30, verbose_name="Téléphone de l'école")),
                ('school_email', models.EmailField(max_length=30, verbose_name="Email de l'école")),
            ],
        ),
        migrations.RemoveField(
            model_name='customizeuser',
            name='school_name',
        ),
        migrations.AddField(
            model_name='customizeuser',
            name='validation_step1',
            field=models.BooleanField(default=False, verbose_name='Validation étape 1'),
        ),
        migrations.AddField(
            model_name='customizeuser',
            name='validation_step2',
            field=models.BooleanField(default=False, verbose_name='Validation étape 2'),
        ),
        migrations.AddField(
            model_name='customizeuser',
            name='validation_step3',
            field=models.BooleanField(default=False, verbose_name='Validation étape 3'),
        ),
        migrations.AlterField(
            model_name='customizeuser',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name="Carte d'identité"),
        ),
        migrations.AlterField(
            model_name='engine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='model',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='customizeuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.school', verbose_name='Ecole'),
        ),
    ]
